name: GitHub Actions Demo On TAGS
run-name: ${{ github.actor }} is testing out GitHub Actions On TAGS üöÄ
on:
  push:
    tags:
      - 'project1/v*'
      - 'project2/v*'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."
      - run: echo "GITHUB_REF=${GITHUB_REF}"
      - name: Imprimir  la tag
        run: |
          echo "La tag que activ√≥ el workflow es: ${{ github.ref }}"
      - name: Imprimir nombre de la tag
        run: |
          echo "La tag que activ√≥ el workflow es: ${{ github.ref_name }}"
      - name: Imprimir nombre de la tag (con bash)
        run: |
          echo "Nombre de la tag: $(echo $GITHUB_REF | cut -d '/' -f 3)"
      - name: Setting variables to execute the build.
        run: |
          echo "APP_NAME=$(echo $GITHUB_REF | cut -d '/' -f 3)"
          echo "APP_VERSION=$(echo $GITHUB_REF | cut -d '/' -f 4)"
  