name: GitHub Actions Demo On TAGS
run-name: ${{ github.actor }} is testing out GitHub Actions On TAGS ðŸš€
on:
  push:
    tags:
      - 'project1/v*'
      - 'project2/v*'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, freebsd, darwin]
        goarch: [amd64, arm64]    
    steps:
      - uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE
      - name: Set up Go
        uses: actions/setup-go@v5 # Uses the setup-go action
        with:
          go-version: '1.25' 
          cache: true
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ðŸ This job's status is ${{ job.status }}."
      - run: echo "GITHUB_REF=${GITHUB_REF}"
      - name: Imprimir  la tag
        run: |
          echo "La tag que activÃ³ el workflow es: ${{ github.ref }}"
      - name: Imprimir nombre de la tag
        run: |
          echo "La tag que activÃ³ el workflow es: ${{ github.ref_name }}"
      - name: Imprimir nombre de la tag (con bash)
        run: |
          echo "Nombre de la tag: $(echo $GITHUB_REF | cut -d '/' -f 3)"
      - name: Setting variables to execute the build.
        run: |
          echo "APP_NAME=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_ENV
          echo "APP_VERSION=$(echo $GITHUB_REF | cut -d '/' -f 4)" >> $GITHUB_ENV

      - name: building the packages.
        run: | 
          cd $GITHUB_WORKSPACE
          echo "current value for goos: ${{ matrix.goos }}"
          echo "current value for goarch: ${{ matrix.goarch }}"
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          export APPVERSION=${{ env.APP_VERSION }}
          make -C ${{ env.APP_NAME }}/

      - name: list packages.
        run: | 
          ls -la build/*