name: Build and publish artifacts
run-name: ${{ github.actor }} is running out GitHub Actions On TAGS ðŸš€
on:
  push:
    tags:
      - 'project1/v*'
      - 'project2/v*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, freebsd]
        goarch: [amd64, arm64]    
    steps:
      - uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE

      - name: Set up Go
        uses: actions/setup-go@v5 # Uses the setup-go action
        with:
          go-version: '1.25' 
          cache: true
      - name: Setting variables to execute the build.
        run: |
          echo "APP_NAME=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_ENV
          echo "APP_VERSION=$(echo $GITHUB_REF | cut -d '/' -f 4)" >> $GITHUB_ENV

      - name: building the packages.
        run: | 
          cd $GITHUB_WORKSPACE
          echo "current value for goos: ${{ matrix.goos }}"
          echo "current value for goarch: ${{ matrix.goarch }}"
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          export APPVERSION=${{ env.APP_VERSION }}
          make -C ${{ env.APP_NAME }}/

      - name: Changing permissions.
        run: | 
          chmod 755 build/*

      - name: Uploading artifact.
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.APP_VERSION }}
          path: build/${{ env.APP_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.APP_VERSION }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.set-upload-url.outputs.upload_url }}
    steps:
      - name: Setting variables.
        run: |
          echo "APP_NAME=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_ENV
          echo "APP_VERSION=$(echo $GITHUB_REF | cut -d '/' -f 4)" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.APP_NAME }}/${{ env.APP_VERSION }}
          release_name: ${{ env.APP_NAME }}/${{ env.APP_VERSION }}
          draft: false
          prerelease: false
      - name: Set upload url
        id: set-upload-url
        run: echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_OUTPUT

  upload-assets:
    needs: create-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, freebsd]
        goarch: [amd64, arm64]
    steps:
      - name: Setting variables.
        run: |
          echo "APP_NAME=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_ENV
          echo "APP_VERSION=$(echo $GITHUB_REF | cut -d '/' -f 4)" >> $GITHUB_ENV
      - uses: actions/download-artifact@v5
        with:
          name: "${{ env.APP_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.APP_VERSION }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./${{ env.APP_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.APP_VERSION }}
          asset_name: ${{ env.APP_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.APP_VERSION }}