name: Build and publish artifacts
run-name: ${{ github.actor }} is running out GitHub Actions On TAGS ðŸš€
on:
  push:
    tags:
      - 'project1/v*'
      - 'project2/v*'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, freebsd]
        goarch: [amd64, arm64]    
    steps:
      - uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE

      - name: Set up Go
        uses: actions/setup-go@v5 # Uses the setup-go action
        with:
          go-version: '1.25' 
          cache: true
      - name: Setting variables to execute the build.
        run: |
          echo "APP_NAME=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_ENV
          echo "APP_VERSION=$(echo $GITHUB_REF | cut -d '/' -f 4)" >> $GITHUB_ENV

      - name: building the packages.
        run: | 
          cd $GITHUB_WORKSPACE
          echo "current value for goos: ${{ matrix.goos }}"
          echo "current value for goarch: ${{ matrix.goarch }}"
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          export APPVERSION=${{ env.APP_VERSION }}
          make -C ${{ env.APP_NAME }}/

      - name: Changing permissions.
        run: | 
          chmod 755 build/*

      - name: Uploading artifact.
        uses: actions/upload-artifact@v4
        name: ${{ env.APP_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.APP_VERSION }}
        path: build/${{ env.APP_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.APP_VERSION }}